### ISSUE TITLE
How to use SPECIFIC_HOST	env variable

### ISSUE THREAD

**Issue by dj-hedgehog** [adi90x/rancher-active-proxy#10]
Thanks for introducing SPECIFIC_HOST for me but can you explain how to use it, please? We should also add the explanation to the README.

**Comment by adi90x** [comment]
Hello, 

Just need to add SPECIFIC_HOST as an environmental value to RAP , to limit it to only containers running on a specific host.
Just use Rancher Host name.
I will add something in the readme quickly
Regards,

**Comment by adi90x** [comment]
Just push an explanation for the environmental value : [Specific Host](https://gitlab.com/adi90x/rancher-active-proxy/tree/master#specific-host-name)

If you need more information do not hesitate !
