### ISSUE TITLE
Redirect non-www to www subdomain

### ISSUE THREAD

**Issue by dj-hedgehog** [adi90x/rancher-active-proxy#11]
We will launch a product soon and decided to enforce the www subdomain and 301 redirect from the non-www version of it.
In Nginx this would look like the below but how do I achieve the first server-block with RAP?

```
server {
    listen               80;
    listen               443 ssl;
    server_name         example.com;
    ssl_certificate      path/to/cert;
    ssl_certificate_key  path/to/key;

    return 301 $scheme://example.com$request_uri;
}

server {
    listen               80;
    listen               443 ssl;
    server_name          www.example.com;
    ssl_certificate      path/to/cert;
    ssl_certificate_key  path/to/key;

    # RAP generated stuff...
}
```

**Comment by fflo** [comment]
Hi Ali,

why are you trying to do the redirect with RAP?
Usually the webserver serving the website(s) does the redirect to the URL preferred.

RAP takes care that you have valid SAN SSL certificates for all hostname combinations valid for access.

**Comment by dj-hedgehog** [comment]
For my project RAP proxies to an Express webserver.
Of course it could do the routing but Nginx is much faster at this. I also don't want to put another Nginx after RAP because IMO that is kinda pointless.

**Comment by adi90x** [comment]
Hello @dj-hedgehog , 

I just push a new version v0.9.0 ( should be building right now ) that enable `_server` configuration .
This enable you to manually set the server block for a given vhost ! 
Do not hesitate to test if everything is working as expected !
