### ISSUE TITLE
Downtime during container upgrade

### ISSUE THREAD

**Issue by fabiomontefuscolo** [adi90x/rancher-active-proxy#29]
Hello,

I'm using RAP and it works very well. Thank you!

But I'm getting 502 everytime I upgrade my WordPress container behind RAP. I checked several times that the option "Start before stopping" was enabled, but during upgrade RAP ignores the online container and  gives 502.

Thank you again!

**Comment by fabiomontefuscolo** [comment]
Well, I found a solution, to my problem. Instead place rap.host on my app containers, I placed rap.host on haproxy load balancer pointing to my app containers. The haproxy is always online and we don't need to upgrade it, so RAP never breaks. I don't know how rancher haproxy can figure out what containers are ready to receive connections, but rap should copy it.

**Comment by andrezaycev** [comment]
+1
but have the same error with sidekick container: for example nginx+sidekick app container
after upgrading rap has old ip in upstream config

**Comment by rtyshyk** [comment]
@fabiomontefuscolo, start before stop just checking that your container started it does not know about your container state, after container started I guess you have (or container base image) has entry point like some db migrations, files permissions, supervisor start, which then stars web server, so during this time you have downtime. I would recommend you to use healthchecks, it will give rancher a knowledge when your container are healthy and old container can be deleted.

**Comment by andrezaycev** [comment]
I found next
 ```
upstream example.com {
        #Acces through rancher managed network
        server 10.42.84.28:80;
    #Acces through rancher managed network
        server :80;
    server localhost down;
}
```

In RAP log

```
31.10.2017 19:20:26ranchergen.1 | level=info msg="[nginx -t]: \"2017/10/31 10:20:26 [emerg] 396#396: no host in upstream \\\":80\\\" in /etc/nginx/conf.d/default.conf:66\""
31.10.2017 19:20:26ranchergen.1 | level=info msg="[nginx -t]: \"nginx: configuration file /etc/nginx/nginx.conf test failed\""

```
Sometimes active proxy have this config - maybe he wrong get container without ip. After it next upgrade for service not helping - only reboot RAP container fix it

**Comment by ValentinOdier** [comment]
Hi,

Just wanted to say i have this issue too. Just like above.
