### ISSUE TITLE
VIRTUAL_HOST support

### ISSUE THREAD

**Issue by davidwindell** [adi90x/rancher-active-proxy#30]
Any chance of bringing back support for VIRTUAL_HOST env vars?

We've just hit the issues with running the original `jwilder/nginx-proxy` on Rancher but our whole network has been setup to use this environment variable.

**Comment by davidwindell** [comment]
Or, at least the option to specify what the label name is (instead of rap.host)

**Comment by khusseini** [comment]
Maybe this helps? https://github.com/adi90x/rancher-active-proxy/blob/master/app/letsencrypt.tmpl

**Comment by davidwindell** [comment]
Thanks, we switched to Traefik 1.4 direct
