### ISSUE TITLE
"a client request body is buffered to a temporary file"

### ISSUE THREAD

**Issue by Braintelligence** [adi90x/rancher-active-proxy#41]
I have things like this in my log:
nginx.1     | 2017/12/27 13:02:32 [warn] 2680#2680: *1431 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000277, client: client.ip.add.ress, server: my.domain.com, request: "POST /v2-beta/publish HTTP/2.0", host: "my.domain.com"

And the number of files is rising.

Is this a problem?

**Comment by adi90x** [comment]
I think it is quite normal for nginx to do that , at least I don't see any RAP specif config or that...
