### ISSUE TITLE
Rancher2

### ISSUE THREAD

**Issue by Xstoudi** [adi90x/rancher-active-proxy#45]
Is rancher-active-proxy compatible with rancher 2.0 ?

**Comment by adi90x** [comment]
I am using it with Rancher 1.6.12, and no idea of the change to v2...
If you try let us know ! If not I may try whenever I have some more time !

Le 20 févr. 2018 15:46, "Xavier Stouder" <notifications@github.com> a
écrit :

**Comment by Q-efx** [comment]
Rancher 2.0 is dropping cattle as far as I understood.

So RAP would need to work within Kubernetes. So RAP would be pretty much dead when 2.0 arrives and people switch :( 

I liked the simplicity though! 

Traefik for Kubernetes is also nice, but has more overhead.

**Comment by adi90x** [comment]
I haven't really look into Rancher 2 at the moment but I am quite sure that
RAP should work with it too !
I don't see any reason they would drop API support...
However, there may be some endpoint config change !
Will check that this week and keep you inform !
As for kubernetes, I have never really use it but may be looking into it in
the future

**Comment by Xstoudi** [comment]
Seems to not work, have you tried it ?

**Comment by vitorfhc** [comment]
Would someone mind giving us some feedback? Is is working?

**Comment by akamustang** [comment]
I tried, got as far as launching rancher on different ports, but was unable to figure out how to launch rancher-agent on different ports and keep it talking to rancher.
Any hints would be appreciated.

**Comment by adi90x** [comment]
Hello,

Rancher 2 is based on kubernetes, so I don't think we can use the same
approach... But I am working on a kubernetes ingress (should be possible to
use it as à load balancer in rancher) that would do the exact same thing
except it will talk with kubernetes API instead of rancher.
Will see if I can make it work with rancher too

Regards,

**Comment by akamustang** [comment]
Ah interesting, thanks for the info.

**Comment by adi90x** [comment]
Hello, 

@mustanggb @vitorfhc @Xstoudi @Q-efx I know it is more than a year old topic , but I just release [Kube Active Proxy](https://github.com/adi90x/kube-active-proxy)

Kube Active Proxy ( a.k.a KAP ) is the same as RAP but for Kubernetes cluster environment
This should therefore work with Rancher 2 ( I have develop it using a k3s environment from Rancher )
Do not hesitate to have a look if you are still using RAP :)

Have a good evening,

**Comment by mustanggb** [comment]
Thanks a lot, I will definitely check it out.

**Comment by adi90x** [comment]
> Thanks a lot, I will definitely check it out.

Do not hesitate to raise any issue or PR to this new appli !

**Comment by Xstoudi** [comment]
Dude, you rocks !
