### ISSUE TITLE
Basic auth does not work

### ISSUE THREAD

**Issue by dj-hedgehog** [adi90x/rancher-active-proxy#5]
Did you try out basic auth as described in the README? I did it (as with JWilder's Nginx Proxy) but the browser never asks for them.

**Comment by adi90x** [comment]
It works for me ...
Are you sure that you mount the correct volume ?  
Do you have a file called after the hostname in folder /etc/nginx/htpasswd of RAP container ?

**Comment by dj-hedgehog** [comment]
This is from inside the container:

```
bash-4.3# ls -l /etc/nginx/htpasswd/
total 8
-rw-r--r--    1 root     root            44 Jan 13 15:38 apidoc.myservice.com
-rw-r--r--    1 root     root            44 Jan 13 15:38 test.myservice.com
```

This is my docker-compose.yml as copied from the Rancher stack itself:

```
version: '2'
services:
  Rancher-Active-Proxy:
    image: adi90x/rancher-active-proxy
    environment:
      CRON: 0 2 * * *
      DEBUG: 'True'
      DEFAULT_EMAIL: contact@mycompany.com
      DEFAULT_HOST: ''
      DEFAULT_PORT: '80'
      RAP_DEBUG: debug
    stdin_open: true
    volumes:
    - /opt/node/rancher-active-proxy/htpasswd:/etc/nginx/htpasswd
    - /opt/node/rancher-active-proxy/vhost.d:/etc/nginx/vhost.d
    - /opt/node/rancher-active-proxy/letsencrypt:/etc/letsencrypt
    tty: true
    ports:
    - 443:443/tcp
    - 80:80/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: proxy=true
      io.rancher.container.pull_image: always
```

**Comment by adi90x** [comment]
Can you also copy you /etc/nginx/htpasswd/test.myservice.com

**Comment by dj-hedgehog** [comment]
That is the content of it: `admin:$apr1$oZD0oz/y$EIaHbK4GUYz5HrX55RF7/.`

**Comment by adi90x** [comment]
Hello, 
Maybe a basic thing to do but did you clear cache/cookies/active connection from Firefox ? 
As I get the same behaviour as you have : nothing is asked when I connect to the website , however after clearing everything it is asking from auth ! 
Firefox ( possibly other browser too ) keep those credential to simplify user experience I guess !

**Comment by dj-hedgehog** [comment]
Oh my god, I forgot to update the IP of the subdomain to the new host.

Imagine I've got two hosts. Both run RAP.
RAP reverse proxies to the container running on another host (the config contains ALL hosts containers config, I will create an issue for this within the next minutes) but the RAP on the host with htpasswd for this subdomain is not considered because it points to the other IP.
