### ISSUE TITLE
Rancher-active-proxy repository not listed in catalog

### ISSUE THREAD

**Issue by gris-gris** [adi90x/rancher-active-proxy#53]
After I added the repository to the catalog and updated the list, it does not appear in the list
![image](https://user-images.githubusercontent.com/16992481/38485721-d800f0ac-3beb-11e8-8a52-6ed138b4835b.png)
![image](https://user-images.githubusercontent.com/16992481/38485753-f688874c-3beb-11e8-9d59-54d42aafb3e2.png)

**Comment by BlowaXD** [comment]
Hey !
Got the same error, did you solve it ?
