### ISSUE TITLE
RAP generates config for containers on all hosts

### ISSUE THREAD

**Issue by dj-hedgehog** [adi90x/rancher-active-proxy#7]
I don't know if this is intended behaviour but it is definitely different compared to JWilder.

I've got two hosts. Both run RAP.
EACH RAP instance includes the configuration for ALL containers using it on ALL hosts.

Example:
Host 1 runs foo.service.com 
Host 2 runs bar.service.com

The config for RAP on host 1 includes foo.service.com and bar.service.com
The config for RAP on host 2 includes foo.service.com and bar.service.com

Is this wanted behaviour?

**Comment by adi90x** [comment]
Yes this is definetly an intended behavior !
Rancher enable to have a private network between all host , and containers maybe started on any available host ( excepted if services is forced on a specific host ).
Therefore, being able to acces containers from any host is the intended behavior !
Jwilder/nginx-proxy connect to docker host and therefore is limited to container running on one host !
In fact , the basic logic with rancher is to be able to acces everything from every host therefore you can have upgrade configuration to support any number of host easily !
In your case , I think the best configuration to work with multihost setup , is to have all data ( ex : config /etc ) in a shared storage ( you could look at [this](https://docs.rancher.com/rancher/v1.2/en/rancher-services/storage-service/) )
But to conclude, yes it is a wanted behavior as it enables to acces any service from any IP/host route to one of rancher host !

**Comment by dj-hedgehog** [comment]
That should be probably mentioned in the readme.

How about an option to limit RAP's reverse proxying to the host itself? Our corporation can't rely on a single proxy for all the trafic.

**Comment by adi90x** [comment]
That could probably be possible , I will look into that option this afternoon !
However , you could have several RAP proxy listening on different IP and they act as failsafe .
If one of the host fail your service are still availble from the other IP no ?

**Comment by dj-hedgehog** [comment]
That would be amazing.

We would have to dynamically reassign the the subdomains to another IP though. We are currently not making use of that but it needs to be considered in the future.

**Comment by adi90x** [comment]
I just push an update to RAP.
You can use SPECIFIC_HOST as an environmental value to defined which host should be look at ! 
Should be working as you expect ! 
I didn't have much time to test it so do not hesitate to report any issue !

**Comment by adi90x** [comment]
Just push a new vesion with a rework logic of handling containers upstream , so this is now clean in the config !

**Comment by Braintelligence** [comment]
Just to clarify:

Assume I have
host1 with IP X.X.X.100
and host2 with IP X.X.X.101

Now I have domains
test1.com with DNS entry to IP X.X.X.100
test2.com with DNS entry to IP X.X.X.101

If host1 is running RAP, will it be able to get a certificate for host2, or do I need to run RAP specifically on host2 as well?
