### ISSUE TITLE
No SSL anymore after upgrading to 8-add-san-certificate-support

### ISSUE THREAD

**Issue by dj-hedgehog** [adi90x/rancher-active-proxy#8]
I tried upgrading to latest from the tag `7-multiple-virtualhost-config` but all of my hosts were exposed without their SSL certificates. Then I went through the tags from latest to oldest to find a working one. 

The problem occurs when upgrading from the image tagged `7-multiple-virtualhost-config` to `8-add-san-certificate-support`.

Do I need to do something to apply this update successfully?

**Comment by adi90x** [comment]
Hello, 
Just pull the image tag latest ( i.e no tag is needed : adi90x/rancher-active-proxy ) 
Those are just development branch and should not be used

**Comment by dj-hedgehog** [comment]
I initially tried with the latest Branch and experienced the same problem.

**Comment by adi90x** [comment]
Do you still experience problem with the latest branch ? 
I push quite a lot of update yesterday

**Comment by dj-hedgehog** [comment]
I will try later today and report back here with the attached generated nginx config. Thanks for reopening.

**Comment by dj-hedgehog** [comment]
Ok, I just checked with the latest image. Nothing can be reached. Here is the content of `/etc/nginx/nginx.conf`:

```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    server_names_hash_bucket_size 128;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
daemon off;
bash-4.3# cat /etc/nginx/conf.d/default.conf


# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}

# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}

# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}

# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}

gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';

access_log off;

# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;

# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";

server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}

# Rancher Services config


upstream bugtracker.myservice.com {
	#Acces through rancher managed network
	server 10.42.173.229:8080;
    server localhost down;
}

server {
	server_name bugtracker.myservice.com;
	listen 80  ;
	access_log /var/log/nginx/access.log vhost;
	include /etc/nginx/vhost.d/default;

	location / {
		proxy_pass http://bugtracker.myservice.com;
	}
}


upstream git.myservice.com {
	#Acces through rancher managed network
	server 10.42.109.128:80;
    server localhost down;
}

server {
	server_name git.myservice.com;
	listen 80  ;
	access_log /var/log/nginx/access.log vhost;
	include /etc/nginx/vhost.d/git.myservice.com;

	location / {
		proxy_pass http://git.myservice.com;
	}
}


upstream registry.myservice.com {
	#Acces through rancher managed network
	server 10.42.109.128:80;
    server localhost down;
}

server {
	server_name registry.myservice.com;
	listen 80  ;
	access_log /var/log/nginx/access.log vhost;
	include /etc/nginx/vhost.d/registry.myservice.com;

	location / {
		proxy_pass http://registry.myservice.com;
	}
}
```

**Comment by adi90x** [comment]
Do you have certs availables in the cert folder for those sub domains ? 
I just start a new environment and it show https part.
Are you sure that you did not put rap.https_method = nohttps ? 
You can also run `rancher-gen --onetime nginx.tmpl /etc/nginx/conf.d/default.conf ` from inside RAP container in order to recreate the template immediatly and see if anything change.

**Comment by dj-hedgehog** [comment]
Yes, certs are in /etc/nginx/certs

Containers only have `rap.host`, `rap.le_host` and `rap.port`
This is the launch-config of rap itself:

```
version: '2'
services:
  Rancher-Active-Proxy:
    image: adi90x/rancher-active-proxy
    environment:
      CRON: 0 2 * * *
      DEBUG: 'True'
      DEFAULT_EMAIL: contact@mycompany.com
      DEFAULT_HOST: ''
      DEFAULT_PORT: '80'
      RAP_DEBUG: debug
    stdin_open: true
    volumes:
    - /opt/node/rancher-active-proxy/htpasswd:/etc/nginx/htpasswd
    - /opt/node/rancher-active-proxy/vhost.d:/etc/nginx/vhost.d
    - /opt/node/rancher-active-proxy/letsencrypt:/etc/letsencrypt
    tty: true
    ports:
    - 443:443/tcp
    - 80:80/tcp
    labels:
      io.rancher.container.pull_image: always
```

**Comment by adi90x** [comment]
Did you tried to relauch the template from inside the RAP container and
then run `nginx -s reload` also from inside RAP ?

**Comment by dj-hedgehog** [comment]
I just executed this in the container:

```
rancher-gen --onetime nginx.tmpl /etc/nginx/conf.d/default.conf
nginx -s reload
```
The resulting `default.conf` is still the same as above.

**Comment by adi90x** [comment]
I just tried on a new VPS  under ubuntu 16.04 , just installing docker+rancher and using you docker-compose.yml and adding 2 containers with same rap label...
Can you copy log from RAP with you start it ?

**Comment by fflo** [comment]
Hi,
I'm running all VPS under Ubuntu 16.04 with latest rancher and I'm suffering the same bug of dj-hedgehog. What's really strange is that a few containers do still provide correct SSL setup, but the majority does not.
But I did not succeed yet to find out why it fails on a few containers only.

**Comment by fflo** [comment]
I can agree with dj-hedgehog that running adi90x/rancher-active-proxy:7-multiple-virtualhost-config resolves the issue.

**Comment by adi90x** [comment]
Hello @fflo  , 
Thanks for using RAP !
I just delete all branch images and I am now gonna tag "working" version, as branch are most of the time use only for dev purpose !
I still recommend using latest image from master branch.
Did you try with latest images ?

**Comment by dj-hedgehog** [comment]
@adi90x Please don't ever delete images we depend on again. Since latest is not working and we haven't figured out the issue `7-multiple-virtualhost-config ` is the only option of @fflo and me.

**Comment by adi90x** [comment]
Hello,
I cleaned all old branchs but I created tag instead !  I will make sure
that one tag point to the branch 7 last commit !
Seems that tag are not properly build by Docker Hub automated build so I
will check and update that asap !

Le 18 janv. 2017 4:16 PM, "Ali" <notifications@github.com> a écrit :

@adi90x <https://github.com/adi90x> Please don't ever delete images we
depend on again. Since latest is not working and we haven't figured out the
issue 7-multiple-virtualhost-config is the only option of @fflo
<https://github.com/fflo> and me.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/adi90x/rancher-active-proxy/issues/8#issuecomment-273502969>,
or mute the thread

**Comment by adi90x** [comment]
Just manually add a docker build ( in progress ) for the tag corresponding to the branch `7-multiple-virtualhost-config` ==> Tag to use :  v0.5.0

**Comment by adi90x** [comment]
I didn't get the point that only above 7-multiple-virtualhost-config was not working for you ! I will check again what changed between v0.5.0 and v0.6.0 !

**Comment by adi90x** [comment]
So if you confirm that v0.5.0 is working on your side , I will make a diff between that tag and master branch and check every change ! ( or possibly create a build of every commit from that point and check where is the problem exactly if you have enought time for that :p  ! )

**Comment by adi90x** [comment]
By any chance could you send me the `letsencrypt.conf` file that is generated with a not working version ? 
Do you use any special characters in containers/services name ?

**Comment by fflo** [comment]
> By any chance could you send me the letsencrypt.conf file that is generated with a not working version?
How can I send you the file(s). Before and after upgrading to :latest ...

> Do you use any special characters in containers/services name ?
No, I'm not using special characters except "-".

**Comment by fflo** [comment]
> By any chance could you send me the letsencrypt.conf file that is generated with a not working version ?

I've send you a copy of my file by email.

**Comment by adi90x** [comment]
Thanks @fflo for the file ! 
I can see anything between v0.5.0 and v0.6.0 that could explain why only some services are not working ! 
I will try to summarize : 

1.  v0.5.0 is working 
2. v0.6.0 is not working
3.  Only few services are not working, nothing special on those : Is it always the same containers that are not working or is it changing ? 
4.  SSL part is not working for some services while certs are inside /etc/nginx/certs.
5.  No special characters except "-" 
6. Certs are correctly created 

Am I correct ? 

Between v0.5.0 and v0.6.0 only changes are : 
- functions.sh => Change how certs are setup => Seems to be working ( Point 4 )
- letsencrypt.sh => Change how certs are handle and created => No impact ( Point 6 )
- letsencrypt.tmpl => Change split to enable SAN certs => No Impact ( Point 6 + file from @fflo that seems correct and consistent with previous version)

If I miss something do not hesitate to report it ! 
If you have some time could you check if v0.7.0 and v0.8.3 are not working ?

**Comment by fflo** [comment]
> I can't see anything between v0.5.0 and v0.6.0 that could explain why only some services are not working !

Ack. Looking at the source code modifications I have no idea what may cause this strange issue.

> v0.5.0 is working

Yes it does. Except I'm missing the san-certificate-support which would be very useful.

> v0.6.0 is not working

Yes, that's correct. All SSL enabled websites now default to the entry abe.611.to execpt m.611.to.

> Only few services are not working, nothing special on those : Is it always the same containers that are not working or is it changing ?

Yes, nothing special. It is always the same containers that are not working.

> SSL part is not working for some services while certs are inside /etc/nginx/certs.

False! The certificate (links) are missing in /etc/nginx/certs. But they are present in the source directory /etc/letsencrypt/live/[domain]/...

Maybe this helps to debug the issue 👍 

> No special characters except "-"

Ack.

> Certs are correctly created

False! The SAN certificate has not been created.

> could you check if v0.7.0 and v0.8.3 are not working ?

v0.7.0 and v0.8.3 are both not working, too.

**Comment by adi90x** [comment]
Yes that is helpful ! I changed the way certs links are made between v0.5.0 and v0.6.0 ! 
And SSL server config is based on whether or not there is an SSL cert ! 
I am gonna focus on this and double check every thing !

For SAN certs it should be working as soon as this problem is solved ( it was part of v0.6 )

**Comment by adi90x** [comment]
I just spot something , rancher-gen-rap was not escaping "-" as it does for other characters ! 
I am gonna add that and rebuild v0.6.0 to test; maybe as simple as that !
If it works I will double check all avaible characters in URL that need to be escape and add those !

**Comment by adi90x** [comment]
@fflo @dj-hedgehog  I just correct Rancher-gen to take into account "-" ,and rebuild v0.6.0 and higher.
Could you try it ?

**Comment by dj-hedgehog** [comment]
@adi90x It works now with v0.6.0. Trying the latest versions soon as well!

**Comment by adi90x** [comment]
Perfect ! Docker Hub is currently rebuilding v0.7 => latest

**Comment by dj-hedgehog** [comment]
v0.7 also works nicely. Thanks a lot for taking the time.
I will also check soon whether the new version helps with me 502 errors https://github.com/adi90x/rancher-active-proxy/issues/6

**Comment by adi90x** [comment]
@dj-hedgehog Did you check latest version ?

**Comment by dj-hedgehog** [comment]
I checked v0.7 and it works fine. you mean v0.8.3?

**Comment by adi90x** [comment]
yes v0.8.3 or latest tag ( just pulling adi90x/rancher-active-proxy with no tag/version)

**Comment by fflo** [comment]
> Perfect ! Docker Hub is currently rebuilding v0.7 => latest

Yes perfect. I can confirm that :latest build is working like a charm. Thanks for your great project!

**Comment by adi90x** [comment]
Perfect ! Do not hesitate to raise another issue , if there is anything I can add to the project !
