### ISSUE TITLE
additional rap. tags

### ISSUE THREAD

**Issue by fflo** [adi90x/rancher-active-proxy#9]
Hey Adrien,

is it possible to add additional rap tags for
- server_tokens [default: on]
- client_max_body_size [default: ???]

I know that it's already possible to configure these settings placing a file per domain to the vhost.d directory but using this way to configure the settings has the disadvantage that a wrong configuration file (syntax) can put the whole rancher-active-proxy setup offline.

**Comment by adi90x** [comment]
Just push a new tag version supporting those 2 directives : v0.8.5 ! 
Tell me if everything is working as expected !

**Comment by fflo** [comment]
upgrading to v0.8.5 and removing the individual configuration files in vhost.d (primary SAN hostname linked to each additional SAN hostname) in favor of a container tag rap.client_max_body_size breaks containers running with SAN certificates.

I've tried downgrading step by step to v0.6.0 with no luck to get the containers back online with no luck.

Restoring the configuration in vhost.d and removing the additional tags gets the container back online using :latest.

**Comment by adi90x** [comment]
Hello, @fflo Is it working with containers not using SAN certificates ? 
No need to downgrade , those label are only support in 0.8.5 and higher ! 
I will try to look into that issue asap.
Do you have an image that need client_max_body_size directive to work ?

**Comment by fflo** [comment]
> Is it working with containers not using SAN certificates ?

Yes, containers not using SAN certificates did work without any issues.

> Do you have an image that need client_max_body_size directive to work ?

Running wordpress containers it's often necessary to adapt the settings to be able to import some themes or other data for installation.
Also webmail containers may need some adaption to allow larger file attachment sizes.

**Comment by fflo** [comment]
Update: updating to :latest breaks other containers, too.

**Comment by adi90x** [comment]
I think I know the problem SAN certificate container several domain name but only one name.
On start I relink certs ( in /etc/letsencrypt/live ) to /certs .
This may break stuff...
As I can not see why adding label to server config could impact SAN certificates.

**Comment by adi90x** [comment]
@fflo : I push a v0.8.6 if you want to try.
I am trying to reproduce your problem, but running into problem with Wordpress image and php.ini `upload_max_filesize` for the moment :p

**Comment by adi90x** [comment]
In fact , rap label is working at least with Wordpress with SAN certificates.
If I set it at 2m I got an error. And setting it at 64m it works perfectly !
Are you sure that you don't have to update your php.ini in wordpress image ?

**Comment by fflo** [comment]
Thank you!
v0.8.6 seems to fix all the issues.

I only had the strange effect that one host did refuse all inbound connections on port 80 and 443 after upgrading to v0.8.6. Stopping, waiting and starting all active RancherActiveProxy services has fixed the problem; restart did not work (port 80 and 443 was offline on another host). I'll keep an eye on this effect and let you know if happens again.

Maybe the issue is a locking bug related to the fact that I'm using shared volumes for the directories /etc/nginx/htpasswd, /etc/nginx/vhost.d and /etc/letsencrypt to be able to move and serve containers on all hosts.

I'm running one instance of RancherActiveProxy on every host. They all share the directories above.

**Comment by adi90x** [comment]
Perfect let me know If you see this strange behavior again !
